version: "3.8"

services:
  app1:
    build:
      context: .
    env_file:
      - ./.env.local
    ports:
      - "3001:3000"
    depends_on:
      redis-stack:
        condition: service_healthy
    networks:
      - default_network

  app2:
    build:
      context: .
    env_file:
      - ./.env.local
    ports:
      - "3002:3000"
    depends_on:
      redis-stack:
        condition: service_healthy
    networks:
      - default_network

  redis-stack:
    image: redis/redis-stack:latest
    container_name: redis-stack
    ports:
      - "6379:6379"
      - "8001:8001"
    restart: always
    networks:
      - default_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  default_network:
    driver: bridge
